server:
  port: 8888

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:stock;DB_CLOSE_DELAY\=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  jackson:
    serialization:
      write-date-keys-as-timestamps: false
    time-zone: Asia/Seoul
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: stock-group
      auto-offset-reset: latest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual_immediate
    template:
      default-topic: stock-adjustment
  batch:
    job:
      enabled: false

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
