
server:
  port: 8889

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: test-consumer-group-1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8085
        specific.avro.reader: true
